apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resume.fullname" . }}
  labels:
    {{- include "resume.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "resume.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "resume.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.resume.image }}"
          imagePullPolicy: {{ .Values.resume.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
