apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: {{ include "resume.fullname" . }}
 annotations:
   kubernetes.io/ingress.class: "public-iks-k8s-nginx"
spec:
 tls:
 - hosts:
   - jrdemo-c4a24be17d2b0bfc980895fd31267ec3-0000.mon01.containers.appdomain.cloud
   secretName: jrdemo-c4a24be17d2b0bfc980895fd31267ec3-0000
 rules:
 - host: jrdemo-c4a24be17d2b0bfc980895fd31267ec3-0000.mon01.containers.appdomain.cloud
   http:
     paths:
     - path: /
       pathType: Prefix
       backend:
        service:
          name: {{ include "resume.fullname" . }}
          port:
            number: 80
